/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registrationUpgradeableSol from "./RegistrationUpgradeable.sol";
export type { registrationUpgradeableSol };
export type { PriceOracle } from "./PriceOracle";
